### PR TITLE
WIP: getting ready for METADATA

### PR DESCRIPTION
**Pull request by Evizero**
I am working on a couple of things to get this ready for METADATA and to add this as an MLDataUtils backend

- update to latest data frames changes (introduction of `Missings`)
- add documentation
- enable preprocessing for higher dimensional arrays (e.g. for image data)

### CODE REVIEW

**Comment by abieler** [comment]
Very nice!

**Comment by abieler** [comment]
Wish I could be of any help. But buried under my day job at the moment...

**Comment by Evizero** [comment]
no worries. you did plenty

**Comment by Evizero** [comment]
I merge this for now since its stale and the whole package is WIP

**Pull request merged**
