### PR TITLE
Syntax fixes for Julia v0.6

### PR DESCRIPTION
**Pull request by abieler**

### CODE REVIEW

**Comment by Evizero** [comment]
LGTM. only comment is that we should also increase the version requirement in REQUIRE

**Review by Evizero — APPROVED** [review]

**Comment by abieler** [comment]
only bump up `julia` version or also `StatsBase` `LearnBase` `DataFrames`?

**Comment by Evizero** [comment]
I think the Julia version should be fine

**Comment by abieler** [comment]
Side note: Do you know if there is somewhere a boxcox transformation and such already implemented in julia?
I did not find anything on a quick google search.

**Comment by Evizero** [comment]
Another minor comment is that travis will fail until the CI settings are updated. same with Appveyor.
If you feel up to it you could push the versions there as well. travis should be simple but the appveyor structure changed since last we updated this and needs a bit of rewrite (see here for a new reference https://github.com/Evizero/Augmentor.jl/blob/master/appveyor.yml)

**Comment by Evizero** [comment]
don't think i saw a boxcox implementation somewhere yet, no

**Comment by Evizero** [comment]
looking good. lets see what CI says

**Comment by abieler** [comment]
Regarding boxcox. That would probably require an `Optim.jl` dependency if we want auto determination of lambda. Do we want to go that route?

**Comment by Evizero** [comment]
good question. I think for prototyping its not a problem (this package isn't registered yet anyway). Once it exists its easier to make decisions about keeping it here or moving it into its own little drop in package

**Comment by abieler** [comment]
so this looks good to me. only nightly tests failed.

**Pull request merged**
