### PR TITLE
WIP: Add more tests

### PR DESCRIPTION
**Pull request by abieler**
Just adding tests to get to ~100% coverage.

### CODE REVIEW

**Comment by Evizero** [comment]
nice

**Comment by Evizero** [comment]
Oh, was I prematurely merging? If so sorry, the tests passed and the code looked uncontroversial so I may have just jumped the gun

**Comment by abieler** [comment]
Yes, I am still adding more tests :) Had me confused for a second though.

**Comment by Evizero** [comment]
Yea the `WIP` in the title should have given me a strong hint, but my brain is somewhere else today

**Pull request merged**
